version: 2.1

commands:
    install-aws-cli:
        steps:
            - run: echoa instalando aws cli
            - checkout
            - run: ls -la

jobs:
    install-dependencies:
        docker:
            - image: ubuntu:latest
        steps:
            - install-aws-cli
            - run: find

workflows:
    workflow1:
        jobs:
            - install-dependencies